### ISSUE TITLE
ngrok domains

### ISSUE THREAD

**Issue by dadastudio** [aphex/vite-plugin-ngrok#1]
Hi, thanks for this plugin. 

How can I make it work with ngrok domains on Free Plan?

Best,
Michał

**Comment by aphex** [comment]
@dadastudio ngrok requires payment for a custom domain in development and a branded domain in production. You can only get ephemeral domains for free.

https://ngrok.com/pricing

**Comment by paallaire** [comment]
@aphex 
If I understood correctly, to make this plugin work, it is mandatory to have a paid account with ngrok?

**Comment by aphex** [comment]
@paallaire no that is not correct. You just need a paid account to use paid features. you can see a breakdown on features here
https://ngrok.com/pricing
