### ISSUE TITLE
domain needs to be fully qualified

### ISSUE THREAD

**Issue by Soviut** [aphex/vite-plugin-ngrok#3]
In my local ngrok.yml I use the `subdomain` prop on my tunnels. However, the Javascript config prefers `domain`. After a fair bit of trial and error, I figured out that the domain needs to be fully qualified `my-tunnel.ngrok.io`, not just `my-tunnel`.

It would be good to update the readme so that this is clearer since the example is ambiguous, showing

```typescript
domain: 'my-domain',
```

I propose it be updated to

```typescript
domain: 'my-domain.ngrok.app',
```

I'd be willing to make a PR for this.

**Comment by aphex** [comment]
@Soviut makes sense to me feel free to send it my way.

**Comment by Soviut** [comment]
@aphex PR is read https://github.com/aphex/vite-plugin-ngrok/pull/4

Feel free to close this thread when it's merged.
